# This rule is not used by the project address-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the local.sdn.cozystack.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: address-controller
    app.kubernetes.io/managed-by: kustomize
  name: ipaddressclaim-editor-role
rules:
- apiGroups:
  - local.sdn.cozystack.io
  resources:
  - ipaddressclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - local.sdn.cozystack.io
  resources:
  - ipaddressclaims/status
  verbs:
  - get
