apiVersion: local.sdn.cozystack.io/v1alpha1
kind: IPAddress
metadata:
  labels:
    app.kubernetes.io/name: address-controller
    app.kubernetes.io/managed-by: kustomize
  name: ipaddress-sample
spec:
  # TODO(user): Add fields here
